### ISSUE TITLE
no account found assertion error

### ISSUE THREAD

**Issue by omija-tea** [Orb-H/Ronnya#2]
![image](https://github.com/Orb-H/Ronnya/assets/92323647/5832c900-982d-4ed3-9625-555b9facb931)
WebSocketClient의 SerachAccountByPattern 멤버함수에서 유저를 찾지 못할시 복구가 안되고 그대로 시스템 다운되는 에러 발생

**Comment by Orb-H** [comment]
assert 없이 null에 해당하는 response 반환하는 방법으로 하면 되나

**Comment by omija-tea** [comment]
그렇게 해야될듯ㅇㅇ 대신 형식을 정해야됨. worker쪽에서 이해할 수 있도록

**Comment by Orb-H** [comment]
이거 유저 검색뿐만 아니라 클라이언트에서 발생할 수 있는 전반적인 오류'를 처리하는' 객체를 만들어서 해결하는게 낫겠다

를 처리하는 → 정보를 담는

**Comment by Orb-H** [comment]
1. HTTP status code처럼 우리 나름대로 상황에 따라 에러 코드를 부여하고 추가적인 메시지를 담는 객체를 사용하는 방법
2. 정상 결과는 일반적으로 dict 형식을 반환하니 '에러 발생 여부'를 나타내는 변수(+메시지)를 해당 dict에 추가해서 나타내는 방법

그거랑은 별개로 치명적인 오류가 아니면 클라이언트가 꺼지지 않게 해야겠군

**Comment by omija-tea** [comment]
사용자 정의 에러를 사용하도록 하자 
[https://nadocoding.tistory.com/74](https://nadocoding.tistory.com/74)

**Comment by Orb-H** [comment]
지금 websocket client에 assert문이 생성자 제외하고 6개가 있는데

1. 전부 raise로 바꾸기
2. 로그인 관련된 부분은 웹소켓 연결도 끊을 예정
    - 만약 끊긴 상태에서 웹소켓 요청을 또 시도하면 또 다른 에러를 raise하도록 구현
3. 유저 검색 부분은 에러만 뱉고 끝

이렇게 할까 생각중.

그리고 assert문 들어간 데가 두 군데 뿐이라 사용자 정의 에러는 투머치인 것 같기도 함. 내장 에러에 메시지만 잘 작성해서 써도 될듯?

**Comment by Orb-H** [comment]
조금 전에 확인해봤는데 except만 잘 싸주면 클라이언트 안 끊기고 잘 실행되는거 확인함. 그거에 맞춰서 main 함수 수정할 예정. 그거랑 별개로 assert는 전부 raise로 바꾸는게 좋을듯
